import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Squirrel Picnic Tables</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>It has been zero</div>
                <div className={styles.count}>
                    <span>0</span>
                </div>
                <div>
                    Days since the last time you made a Squirrel Picnic Bench
                </div>
            </main>
        </div>
    );
};

export default Home;
